namespace: xkdeco
dest: ../src/kiwi_generated/resources
translation_file_name: '{}.json'
translation_dest: '%TEMP%/assets/xkdeco_extra/lang'
json_pretty_print: false
export_format: yaml
materials:
  - xkdeco.xlsx
block_templates:
  - xkdeco.xlsx
blocks:
  - xkdeco.xlsx
block_tags:
  - xkdeco.xlsx
creative_tabs:
  - xkdeco.xlsx
shapes:
  - exported_shapes.json
