namespace: xkdeco
dest: ../run_client/kiwipacks/test.zip
#translation_file_name: '{}.json'
#translation_dest: '%TEMP%/assets/xkdeco_extra/lang'
json_pretty_print: true
includes:
  - includes
materials:
  - test.xlsx
block_templates:
  - test.xlsx
blocks:
  - xkdeco-blocks.csv
creative_tabs:
  - test.xlsx
