name: Generate pack

on:
  push:
    branches: [ "production" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#        with:
#          persist-credentials: false
#          fetch-depth: 2

      - name: Read configuration
        id: config
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: ${{ github.workspace }}/script/pack_config.yaml

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ steps.config.outputs['namespace'] }}.xlsx

      - name: Set up Python 3.10
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          python script/main.py pack_config.yaml

      - name: Upload destination file
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.config.outputs['namespace'] }}
          path: run_client/kiwipacks/
          compression-level: 0

#      - name: Reset the last commit
#        run: |
#          git --version
#          git config --local user.name "GitHub Actions Bot"
#          git config --local user.email "<>"
#          git status
#          git reset --hard HEAD~1
#          git push --force
